### ISSUE TITLE
Method 'failed' not found for invocant of class 'Slip'

### ISSUE THREAD

**Issue by tony-o** [perl6/tap-harness6#7]
Running a benchmark for this vs `prove` vs `flow` - I'm receiving this error while running prove6 - any ideas?

```
tonyo@mbp:~/projects/benchmark/Bailador$ /Users/tonyo/.rakudobrew/moar-nom/install/share/perl6/site/bin/prove6 -I=lib t/
t/01-route-existance.t ..... ok
Method 'failed' not found for invocant of class 'Slip'
  in sub MAIN at /Users/tonyo/.rakudobrew/moar-nom/install/share/perl6/site/resources/05C7ED85897FC8EEDD8A30A4B34FD1DFD2E691D0 line 48
  in block <unit> at /Users/tonyo/.rakudobrew/moar-nom/install/share/perl6/site/resources/05C7ED85897FC8EEDD8A30A4B34FD1DFD2E691D0 line 63
```

**Comment by Leont** [comment]
Do you consistently hit this issue, or only with that particular module? I've never ran into this issue. Due to the way error reporting interacts with promises I'm not even sure if it really comes from that line or is hidden behind a promise (I'm not seeing where either would come from right now).

I'm not sure a benchmark makes much sense. The tests themselves should take way more time than the harness, and TAP::Harness is actually designed to be parallel (though that's still suffering from a bug in rakudo/moarvm).

**Comment by tony-o** [comment]
I’m running into the issue with every module I attempt to test with ‘prove6’ - I don’t know if the issue is with TAP::Harness or not, I’d suspect it’s somewhere in the bin script.  I’m benchmarking the actual running of test suites via `prove`, `flow`, and `prove6`

**Comment by Leont** [comment]
Is this still an issue or can it be closed?
